### ISSUE TITLE
Investigate if any slashCommand handler actually needs `QString &`

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#304]
We might be able to replace all of those string references with const string references. Might make meaning clearer, since I think a command handler should not be modifying the command string itself ?

**Comment by PsiLupan** [comment]
I personally know that the EmailSend console command will likely need to be sanitized before being put in the DB, since it's just sending a raw string, but that should probably be handled in DataHelper.

I don't think any other commands necessarily need it from my experiencing glancing over them and setting up the midRef / splitRef instances.

**Comment by eos428** [comment]
A simple check with CTRL+H for replacing "QString & " with "const QString " gave zero errors, so that means those QString are never modified in those slashCommand functions. I will go ahead and add this into my PR I guess.

**Comment by nemerle** [comment]
`const QString &` would be bettter :)

**Comment by broxen** [comment]
Resolved in #354
