### ISSUE TITLE
Remove segs_game_dbschema.png from the repository ?

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#307]
Git does not work well with binary files that change often, maybe we can use wiki for 'current' and 'release' db schema's visualization ?

**Comment by broxen** [comment]
I agree. The wiki would probably work better and it would be easier for others to contribute to, since dbdesigner.net doesn't really allow collaboration. We lose a tiny bit of visual information (intertable relationships) but I think it's minimal.

Also, if we're able to clean up the serialization a bit (remove superfluous indents etc) it might be a bit easier to read.

Further, what's the proposed plan for DB schema updates with dbtool. Will they be able to rewrite those serializations? I ask, because is the wiki going to also become a tool for proposed changes to the schedule, or simply a record of current/release schemas. This may help in writing iterative db schema patches (in the future)

**Comment by nemerle** [comment]
what I imagine, is having `dbtool migrate` command that will run selected `migration` scripts from migrations directory. No idea how feasible that will be :)

**Comment by broxen** [comment]
Sounds good.

So wiki would have `release` `current` and `proposed` schemas. I'll open an issue later for converting segs_game_dbschema.png to the initial current wiki page. Should be a good non-programmer issue for some of the newcomers looking for ways to contribute.

Can we open the wiki up to contributors? Or do they have to be members of the SEGS org? How best to allow contributions there?

**Comment by nemerle** [comment]
No such luck with wiki-editing :/
Sadly, while github stores to wiki as a hidden repo, it's not easy to get to, or do PRs agains.

**Comment by broxen** [comment]
Is there a better solution? Maybe http://www.vertabelo.com/

**Comment by broxen** [comment]
sqldbm.com seems like it is more powerful?

I'll work on converting the dbdesigner.net schemas to sqldbm.com and will share.

**Comment by broxen** [comment]
hrm.. only downside is that it doesn't have sqlite as a database type... though I suppose we could build in mysql and export?

**Comment by broxen** [comment]
Will submit a PR to remove png from codebase, but as a summary of our discord conversation:

- Continue using dbdesigner.net for database mapping
- Need to update segs_game with latest changes, including proposed changes to PlayerStruct (re: emails) and SuperGroups table (SGData struct), clearly mark proposals as "proposed"
- Add wiki page for database here: https://github.com/Segs/Segs/wiki/DB-Schema-and-Proposing-Changes
- :question: Wiki page needs a host for the database schema png files, so we should find a home for those. Perhaps segs-data repo?

**Comment by ldilley** [comment]
We should be all set moving forward. Doxyfile has been updated with the appropriate IMAGE_PATH @broxen will upload to. Once the image is uploaded, the `@image` tag used in the proper file, and the doxy content is regenerated, the image should appear on http://doxy.segs.io/.
