### ISSUE TITLE
ID UI Does Not Change Experience after First Login

### ISSUE THREAD

**Issue by GitSomeTab** [Segs/Segs#320]
### Expected behavior:
Character Creation should be final

### Actual behavior/symptoms
By Navigating to the ID UI the user is able to "retcon" their character creation choices, including powersets and character name.

### Steps to reproduce behavior/symptoms
-Create a character (actual choices are irrelevant)
-Navigate to ID (Menu -> ID)
-Observe editable name (It's actually the default selected field)
    Note: Modifying the field and logging out does not allow changes to persist.
-Select "Back"
-Observe ability to select new choices. 

Note: Pressing "Back" repeatedly has all kinds of issues that I don't think are worth reporting (as the behavior shouldn't be possible in the first place).

### SEGS version
0.4.2

### Operating system
Windows 10 Pro

### C++ compiler and version
N/A (downloaded pre compiled)

**Comment by broxen** [comment]
Hello GitSomeTab!

Thank you for submitting this issue. This is obviously undesired behavior.

I've been unable to replicate it on the current build 71ac841, so it's possible that this has been fixed since our release exe was made. That said, I'll keep testing and will post my feedback.

If anyone else can replicate this, please post your build version, and operating system. Thank you!

-brox

### SEGS version
build 71ac841

### Operating System & C++ compiler version
Qt 5.9.4 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.1 20180130 (Red Hat 7.3.1-2)) on "xcb" 
OS: Fedora 27 (Workstation Edition) [linux version 4.15.13-300.fc27.x86_64]

**Comment by GitSomeTab** [comment]
I suggest we close this one; I was finally able to get up to date with master and I can see that it's been fixed.
