### ISSUE TITLE
NetCommandManager should build per-access-level command lists

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#376]
Currently all commands in `void NetCommandManager::addCommand( NetCommand *cmd )` are added to the same `m_commands_level0` array, we should have per-access-level arrays, or better yet a:
```cpp
std::map<int, std::vector<NetCommand *cmd> > m_access_level_commands;
```
and then in `NetCommandManager::SendCommandShortcuts` we should send all commands from the player's access-level and those from levels below.

**Comment by dracc** [comment]
So, using initial findings of #416, do we have any indication that only the clients accessible netcommands should be sent? It seems the five currently sent commands are required iregardless of client access level. Client does not complain when higher access level commands are sent and, as far as I can tell, it does not present them to the user nor allow them to be used.

**Comment by nemerle** [comment]
NetCommands are commands that are sent from the server to clients. Basically it allows the server to register a shortcut to a specific command, and then using that shortcut 'run' the given command later.

**Comment by dracc** [comment]
Yes. The fact that they are (more or less) shortcuts, I've deducted from the code.
The question is, are they supposed to be sent only to the clients with the correct access level (or higher)? Because the client crashes on entering world unless the first five are sent (in that specific order) and all access level accounts accept the full list without complaints, where they if only sent their specific allowed netcommands give errors about X unused bytes (or crash, because the first five are level 3 and not all accounts are >=3).

**Comment by nemerle** [comment]
Right now the server always assumes that client will understand the first few commands ( it uses hardcoded time/time scale/time step scale indices )

**Comment by broxen** [comment]
I feel like we were really close to completing this. What's the verdict @dracc ?

**Comment by broxen** [comment]
Segs/SegsEngine will resolve this. Closing.
