### ISSUE TITLE
Catch cereal exceptions

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#388]
Cereal will throw exceptions during serialization of invalid data
We should wrap all cereal functions to gracefully accept those failures, and log the errors.
looking at this https://uscilab.github.io/cereal/assets/doxygen/structcereal_1_1Exception.html
catching cereal::Exception should be enough.

**Comment by ldilley** [comment]
For an example of exception handling, [see the following lines from binConverter.cpp](https://github.com/Segs/Segs/blob/master/Projects/CoX/Utilities/BinConverter/binConverter.cpp#L182-L218). Rather than catch any/all exceptions however, we want to specifically look for `cereal::RapidJSONException` and wrap the necessary statements that might throw such an exception in a try block. We also do not want to exit in all cases, but continue on and log/note the warning as previously mentioned.

**Comment by nemerle** [comment]
As of f9cb381 this is `done`
