### ISSUE TITLE
output.log is never reset and can grow indefinitely

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#602]
### Summary
output.log can grow indefinitely. We should probably put some kind of cap on it's size, and have it reset every X number of sessions.

My own log exceeded 700MB before I deleted. Admittedly, I was doing a lot of movement testing, with a lot of output over dozens and dozens of sessions, but still, that's huge.

**Comment by Magentah** [comment]
If there's a lot of sessions connected and there's a lot of logging enabled, the log files are going to get really big really quickly. I think another option would be to separate out the logging types to their own files, e.g. one for input, one for location, one for mapevents, etc. Maybe have it be configurable in cases you want to easily see multiple log types at once? In addition, doing logs by datetime would somewhat limit how big the files would get due to creating a new file each day.

**Comment by broxen** [comment]
Good ideas. :+1:

**Comment by broxen** [comment]
This seems simple enough, but important. Marking as release-blocker for v7

**Comment by miles200** [comment]
Something like this? I'll have a look at adding some date stuff 

![image](https://user-images.githubusercontent.com/35471210/52535320-d7058500-2d44-11e9-9794-21ea85aba963.png)

**Comment by miles200** [comment]
With dates... Will create a new file for each day

I'll add a 'Purge' button into SEGSAdmin which will grab all files with a date < today and delete them

**Comment by miles200** [comment]
With dates... Will create a new file for each day

![image](https://user-images.githubusercontent.com/35471210/52535473-a9b9d680-2d46-11e9-811a-8158705f47ff.png)



I'll add a 'Purge' button to SEGSAdmin which will grab all files with a date < today and delete them
