### ISSUE TITLE
The client appears to have magic numbers for ent_db_ids. Are they important?

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#751]
### Summary
The client appears to have some kind of magic numbering of ent_db_ids that seems to matter somehow. Is it really important and why? ❓ ❓ ❓ 

Giant hug to whoever uncovers some sort of reasoning.

From a discussion with @eos428 and @nemerle in Discord:
```
// client in tasklists
task_item->location.ent_db_id = task_idx + -100 * task_dbid - 400;

// client in contactlists
npc_contact->m_location.ent_db_id = index - 200;

// in compass
contactDestination.ent_db_id == g_IdxSelectedTask - 400 // g_IdxSelectedTask == task_idx
```
```
so,  from all of this we have this :map: :
EntIds:
  0 - 200 ' Doors maybe' ?
  200 - 400: Contacts ?
  400-???
  For every task [task_db_id]
    +0-100  per task locations
```

Also tagging @ZopharShinta as we've been discussing it.

**Comment by cocanium** [comment]
When you select waypoint on a contact(LUABot in this case) it sets the destinations ent_db_id to -200.
![LUABot](https://i.imgur.com/52JPdmF.png)

This is what happens if you select waypoint on LUABot Test
![LUABot Test](https://i.imgur.com/Yv1MYkG.png)
It seems that LUABot is -200 and LUABot Test is -199.

However, when ever you select LUABot again it doesn't set the id to -200 again for some reason, but it sets it's location?
![Back To LUABot](https://i.imgur.com/6D7Ah2Q.png)

The dest_index sometimes counts by 2s (2,4,6,etc) instead of just dest_index++

**Comment by nemerle** [comment]
Since we're moving to fully custom client now, the problem of defining/using special entity ids is entirely up to us :smile:
