### ISSUE TITLE
Character Creation Bug

### ISSUE THREAD

**Issue by YellowAdder** [Segs/Segs#753]
### BUG DESCRIPTION
A deleted and then remade character _with the same name_ does not start out as a new character and instead retains some information/settings of the previously deleted character.

### To Reproduce
1. Create a character named "Shazam"
2. Enter the world. (Outbreak)
3. Use /mapmenu to transition to Boomtown (or any other map)
4. Delete that character.
5. Make a new character, also named "Shazam"
6. Enter the world.

### Expected behavior
The character expects to enter the Outbreak map.

### Actual behavior
The character unexpectedly starts in Boomtown. It is possible to repeat this behavior of deleting and remaking a character to log into the previous character's last map.

Note that deleting the character, then shutting down and restarting the server before remaking him, results in the expected behavior. (i.e., The character spawns in Outbreak.)

### SEGS Version
0.6.1

**Comment by broxen** [comment]
Thank you for reporting!

**Comment by broxen** [comment]
Can you confirm that this still happens if you leave the server running but completely restart the client?

**Comment by 0Anarchium0** [comment]
I've tested two ways with varied results. The first deletes the character before restarting the client, the second after restarting.

### First Method

1. Create a character named "Blue Brute".
2. Enter the world. (Outbreak)
3. Use /mapmenu to travel to Galaxy City.
4. Delete the Character.
5. Exit and then restart the client.
6. Make a new character named "Blue Brute".
7. Enter the world.

#### Result

In this case, it behaves properly. The newly remade "Blue Brute" starts inside Outbreak.

### Method Two
1. Create a character named "Blue Brute".
2. Enter the world. (Outbreak)
3. Use /mapmenu to travel to Galaxy City.
4. Exit and then restart the client.
5. Delete the "Blue Brute".
6. Make a new character named "Blue Brute".
7. Enter the world.

#### Result

In this case, the bugged behavior appears and the character starts in Galaxy City instead of Outbreak.

**Comment by broxen** [comment]
Method 1and 2 appear to be the same? Typo?

My fear is that this is a client bug particular to our version. It warrants further investigation, but it seems that something is stuck in memory and the client recognizes the character name and makes assumptions about the character (loading prior zone, GUI, etc.)

**Comment by Magentah** [comment]
The difference is deleting the character before or after restarting the client.

**Comment by broxen** [comment]
Does the bug appear only when creating the new character in the same slot? Or does it work normally in a different slot?

**Comment by broxen** [comment]
That hints at this being server side, with our login system failing to reset memory associated with a particular slot at charsel. 

I'll have to dig in further, but feel free to propose a solution if you (or anyone else) finds one.

Appreciate you filing this report @YellowAdder
 and I greatly appreciate @0Anarchium0 and @Magentah for assisting with testing and reviewing this as well.

**Comment by miles200** [comment]
Same character name is a red herring, it seems to be the slot idx , still investigating, but if you delete character "Bob" from slot 0, then create a new character called "Miles" in slot 0, the same issue occurs regarding map

**Comment by miles200** [comment]
@nemerle @broxen 

MapInstance is not being reaped, the map name still shows in the client title bar "City Of Heroes: Talos Island" once back at login screen... could this play any part?

**Comment by miles200** [comment]
Looks like the map session is never marked for reaping in `MapInstance::on_disconnect` .. am I on the right tracks here? 

From reviewing output, map is spun up on first connect with fresh launch of client, after log out (no other entity on map), then log in again with no exit or restart, map isn't spun up again so I'm assuming it's never spun down? My understanding is it should be if no other players on the map?

**Comment by Magentah** [comment]
MapInstance::spin_down() is commented out and not implemented currently. I imagine this is intended to handle the session reaping.

**Comment by miles200** [comment]
Thanks Magentah. Shouldnt reaping happen on disconnect rather than spin down as we are only reaping the client that's disconnecting at that point?

**Comment by broxen** [comment]
Well when a user disconnects it should reap their session, but perhaps during a character switch it's keeping that session alive and assuming the same values for entitydata.

spin_down would be when the MapInstance is destroyed, which I thought happened when everyone left the instance, but the reality is that it should probably happen only if the instance is empty for longer than X amount of time. Maybe a few hours, or maybe customizable.

I would guess that the issue here is in reaping the link when a user disconnects.

**Comment by Magentah** [comment]
I think that reaping is automatic based on a timed interval, setup during MapInstance::start(). This automatically reaps all the stored sessions that are inactive.

The bug may be logging back in before the session is reaped?

**Comment by miles200** [comment]
I could be misunderstanding the code, but it looks like we have to mark_for_reaping before it gets picked up by the auto reaping methods. For instance similar code in GameInstance, on disconnect mark_for_reaping is used but it isnt done currently in MapInstance on disconnect

**Comment by Magentah** [comment]
Ah quite possibly, I’m not at home so looking through on mobile browser, I could be reading it wrong. I can take a look at fixing this soon if no one else takes it.

**Comment by miles200** [comment]
I'll give it a bash first if that's okay? Want to get stuck into the game code a bit more so will probably be a good learning experience for me 😁

**Comment by Magentah** [comment]
Sure! I may be able to answer questions, I done some stuff with sessions before for some transfers.

**Comment by miles200** [comment]
Okay nice thank you 😁
