### ISSUE TITLE
Installation Instructions Typo Readme.md

### ISSUE THREAD

**Issue by kezlyr** [Segs/Segs#757]
Was going through the [installation guide](https://github.com/Segs/Segs/blob/develop/Projects/CoX/docs/README.md) to install the client and noticed a typo/confusing version statement.

Under "REQUIREMENTS AND NOTES"
> A copy of the CoH client from Issue 1 (beta) version 0.22.

Under "INSTALL & CONFIGURE THE COX CLIENT"
> SEGS will only communicate with the CoH client from Issue 0 (version 0.22).

The magnet link is the same for both references, implying that this is a typo, but pretty big chance a non-techy user will see this and briefly implode before downloading the same client twice. I also recommend strictly referring to everything as CoX and strip out CoH completely. I played since launch and I know there's a difference in the game before CoV came out, but consistency and standardization is our friend.

Also if you want me to spice up these instructions with some pictures so there's 0 confusion for anyone (and admins can steal the instructions for their servers), just point me to a page on the Wiki. And any other documentation worth updating.

**Comment by valcryst** [comment]
Hey @kezlyr it's definitly a typo, thanks i missed it.
I found some more and already prepared another PR for docs next days.

**Comment by broxen** [comment]
We should simplify the docs as much as possible to maximize utility, but also to ease maintenance of the documentation moving forward.

That said, I don't know what specific docs you're referring to. Previously we had two READMEs, each with a specific audience.
1. One in the main (root) folder that was aimed at Developers looking to contribute or compile their own server, with links to those looking to download/install/play. This also serves as our readme for GitHub.
2. The second in a project folder, with the intended audience of end users downloading the pre-compiled release packages from GitHub. This 2nd README is copied to the `out` directory at build, so that it would be bundled with releases, but also provide an easily accessible resource for users POST-build. It's purpose was to walk a user through setting up the client and connecting to the server.

Which files specifically? We should update them all and store them where it makes the most sense. This may require a tiny bit of editing in the cmakelist.txt file that copies readme's to the output folder, but let me know and I can guide through that change.
