### ISSUE TITLE
Server data folder names are case sensitive

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#84]
Server looks for `CoreData`, `Data`, and `data` folders during initialization.

This isn't much of an issue on Windows, which does not have a case sensitive file system, but may present problems on Linux during server setup. Additionally, for organization, it may be best to maintain a consistent naming schema for data folders.

My proposal is to enforce a consistent naming format for data files moving forward, and reorganize the current folders as below:
```
./README.txt       # proposed installation guide
./settings.cfg     # proposed name for local_1.cfg
./data/            # data folder for client data (.pigg) files
./data/bin         # data folder for extracted bin files
./mapviewer/       # data folder for mapviewer utility
./scripts/         # lua scripts folder
```

If there are considerations I've overlooked, please share them in the comments below.

**Comment by ldilley** [comment]
This has mostly been taken care of in 48aed7f and 7117bec. The README.md file can essentially take the place of README.txt since they would both be ASCII text files. The file could reference an external link for installation such as the project wiki or https://segs.nemerle.eu/developers.

It would also be a good idea to point out the purpose of each directory in the READMe, on the wiki, and/or at the aforementioned link.

**Comment by ldilley** [comment]
Added new wiki page, [Important Files and Directories](https://github.com/Segs/Segs/wiki/Important-Files-and-Directories), for reference.
