### ISSUE TITLE
How does the leaked source code impact SEGS development?

### ISSUE THREAD

**Issue by Baaleos** [Segs/Segs#875]
Just want to check to see if anyone on SEGS team has had a look at the source code that has allegedly been leaked which includes issue 24 functional COH server.
Is this something that could accelerate development of Segs?  (Within legal confines)

**Comment by dracc** [comment]
IANAL but I firmly believe that the leaked source has only done this project harm.
Looking at the leaked source should result in a ban from contributing to this project IMO as it makes the legality questionable.

**Comment by broxen** [comment]
The only way I can see the leaked source helping to advance SEGS is with strict Chinese Wall Protocols in place to endure that no code is explicitly shared or copied.

This blog has some info on the practice
https://auriga.com/blog/2013/ethical-walls-in-software-development/

**Comment by Baaleos** [comment]
I agree that no illegally obtained source code should be put into SEGS- license compliance an all.
However if a functional emulator springs up in the next week, what will that mean for SEGS?

**Comment by broxen** [comment]
Hard to say.

Our objectives are broader in scope than a pure i24 server emulation. We'd like to have a custom client and be completely detached from NCSoft

**Comment by Baaleos** [comment]
Just curious if there is even observable behaviours that could assist SEGS?
Eg: packets, op codes etc

I assume server side pigg date would be a no-go area, since it was never legally released. Powers, enemies etc would probably need to be ‘guessed’ or ‘derived’ outside of looking at leaked material.

**Comment by PsiLupan** [comment]
SEGS currently has all implemented packets and opcodes, save for some things like creating a Bug Report. Powers and the likes are in the client data. Navmeshes were part of the client back when versus i24.

The best way to contribute without going too far, imo, would be any math for things like defense, how long a status effect lasts, regen rates, etc. that weren't documented too well.

**Comment by broxen** [comment]
Well in terms of power data, we have all that info because later clients released it publicly.

I'm not entirely sure that having access to the world would continue to provide much benefit at this point.

Perhaps if we wanted to move to a newer client and wanted to packet sniff a setup server, but even then I feel like we'd be toeing the line again, because vicariously it relies on leaked code.

**Comment by broxen** [comment]
Marking this as Question AND Good First Issue so that it can be seen by newcomers to the project. Will open a new Issue to rewrite our Contributing docs to make it clear that we are a Clean Room environment and that no leaked code can be used, or should be shared with the project or on our github.

**Comment by kwantumhab** [comment]
Sorry to say this and sorry if i will hurt anyone's feelings(i will and i am sorry i was watching this project since its came up from the day when ncsoft stopped the other emulation software efforts an i am loving the whole COH project and the game itself); but i will say it.... 

With current internet time measurements; this project is older than the building of pyramids and the dying date of the dinosaurs; and resulted almost nothing progress... You guys achieved almost zero productivity almost during the entire period while the server was offline and shut down... This is a developing speed that this project will never be seen on the sunlight until 26th century's end(Around 2690's AD). 

The source code is not making this project any harm. With the current attitude it makes utterly unnecesary.  Why? Becouse if you are using "the ethical wall" you mentioned before, this will be the death of it like it was during 2012-2017... you could take a peak of what is working and how on the source... i think the source would be helping you to make a working system, however i doubt that the result will be a useful thing... babbling about "higher scope than just emulating a working i24" first you should make something that worth the name other than "yaay we have a working login server, AND after 5 years it is actually remembering your characters..." That is 5 years work. Congratulations.(the 5% completion is a VERY VERY bold statement in the faq's... also there is almost zero code change in what? 10 months?? Also how are you gonne do this a clean way?! Sniffing, reverse engineering even extracting the sources is violating the terms of the usage and the clean code using that you mentioned above... so what are we talking about?!?! how is this different from obtaining the code? it is both not so legal people!....  I smell some Hippocracy around here... How are you gonna program something if you wont try to figure it out how it was working actually...? but doing so it is not legal either... so why is this even a question about a project that relys on a information that is not legal to obtain in any way?! ) *sigh* least use the code as guideline... there are a 4000 page manual floating around of theese type of servers... use them for at least ideas to progress....

Conclusion: if you dont peek in the codes(i dont recommend copying it i have to be clear about it, just looking in it... Strictly) you will never come out with any useful more then like this, is in this current state. This could be a very good project... but not with the whole i-use-the-real-code-or-not dilemma delays and such...

Sorry if i hurt peoples feeling so i apologize.Its just... it was on my mind for a ling time now...

**Comment by Baaleos** [comment]
I’m sure no ones feelings are hurt- but they did make a conscious decision to approach Segs with the intent of making a Legal server emulator.
The legality hinges on being able to reproduce functionality without using copyrighted code.
While I acknowledge that NCSoft would never be the wiser- the Segs team would however know if they breached any copyright.
Granted the source leaks does make the Segs project somewhat moot- everyone is using the leaked code- I don’t think anyone will give up using the leaked code to use a viable legal replacement.

To clarify- 
When each of us bought a copy of COH- we were given rights over that copy of COH and the ability to interrogate and observe anything from the content on those CDs or digital downloads.
So when the client sends packets along the network- you are legally allowed to observe those packets- and if you learn something from those packets and can extrapolate what response is required from guess work and experimentation- NCSoft can do fuk all. 
This is legal emulator creation.
NCSoft don’t have the monopoly on any networking protocols or legal protection over any 3rd party software that just happens to use the same packet system etc - as long as it can be proven that their code was not used to construct or learn about the packet system.

What would make it illegal is by looking at the source code to get a head start on development. Then the SEGs project becomes derived work.

I agree with you totally on the relevance of the SEGs project in the shadow of source leaks.
When there was no source leak- SEGS was the last hope for COH fans.
Now the source is out there- and NCSoft can’t stop everyone from running their own private server- so why even pursue an emulator?

I personally would prefer a project aimed at converting the NCSoft source to Linux and/or docker images etc.
Make it possible to run the map servers on less memory/cpu systems etc.

**Comment by broxen** [comment]
Hello @kwantumhab. Thank you for your input. I can sense your frustration, and I appreciate your passion for our project and understand your disappointment in an apparent lack of progress here. Let me speak briefly to the direction of SEGS. @nemerle has been hard at work.

SEGS has different objectives than the other City of Heroes projects online. Those other projects rely on the leaked source code, and are leveraging it to "continue" the game in perpetuity. SEGS is focused on providing a game engine and client for MMO play that are completely independent of NCSoft. This is a slower, more difficult path, but one that will ultimately result in a product free of the legal concerns that plague other endeavors. More importantly, it means that looking at the leaked source doesn't really further our goals. Once the new SEGS Engine and Client are building and communicating, we can build in any direction we like, and can choose (or not choose) to replicate any functionality from City of Heroes without needing to know which Packets the client sends or receives. As a short aside, we already have all of the packets mapped. 

But allow me to address your only question directly:
_Why pursue an emulator?_ Reading between the lines above you'll see that SEGS is moving beyond a mere "emulator." But disregarding that for a moment: there are multiple answers to this question, but perhaps the most important answer is Passion. The same kind of passion that drove you to write this post, drives Nemerle to continue working on SEGS, and it will drive the other devs that choose to contribute to submit pull requests.

If you don't share that Passion for SEGS specifically, with it's specific goals, then don't contribute. This is the beauty of the open source world. On the other hand, if you find our end-goal exciting, we can always use more passionate developers.

I personally value your input regarding a conversion of the NCSoft source to Linux, and improving server efficiency. I think those are fantastic targets, and ones that absolutely should be a priority, but the truth is, those objectives aren't shared by the SEGS project and won't ever be. SEGS has no interest in improving the leaked source. 

To be frank, this isn't the best forum to get your passion for improving the leaked NCSoft source heard. I would try the Ouroboros Project or Homecoming or other private server projects that have made utilizing the NCSoft source part of their development path.

All the best.

_Edit: ahh I realized @Baaleos jumped in with a response and I conflated your two posts together. My apologies for any confusion there. I think my sentiment remains the same and I'll let it stand as written._

**Comment by kwantumhab** [comment]
Oh guys thank you for the rich response. :D(Really i am. Theese kind of responses are very rare theese days.) So once again:  I hope i did not overstepped some boundaries, that was not my intention there. 
I also were a player back in the days on the original servers, i did stepped in the game around the I6 or I7 ~ so i had the feeling that being robbed from something what thousands were loved when it was shutdown...

Also i might have to clarify some things... Back then You guys and nemerle were the only hope to keep this game intact and it would be an unfair thing to you to throw you away just becouse we have the original... I mean It was a very unlikely happening (i mean what were the odds for this leak??) I were never imagined that the most favorite games for me all times will be leaked as a FULL intact server will be out one day.

But that is not the point, what i do say to you is CONTINUE the work guys. Just dont make obstacles to yourself. Thats all. I know that his isnt the best forum for this kind of conversations, so  i wont push it becouse we all know that the leak is illegal. Period. However;I will still be an observer and if i can i help with you guys. I was just puzzled by the speed of development...(I can do some programming and 3D designing BTW if you interested but i only programming mostly in delphi/rad and not C sadfully...)

I will answer both of you guys becouse it is more simpler.

I like the idea of making this smaller, and less resource consumer than the server is itself - i mean by the original - if you do this and this will be a better faster an more memory friendly it is a well go... I did tried and watched always will check your progress... - i never said that is pointless...  i said it is pointless IF you are not taking advantages on certain aspects(and for that you lose dev. speed)... but ofc its just an opinion wich you propably have enough, so sorry once again.

Also: Why to pursue a custom built emu? I never questioned that. If you make this you will have a - SOMEWHAT - legal emulator like the WOW servers and such... Those are not containing any of the real code also. i agree with this.

But @broxen  i never questioned the raison d'etre of segs(There was IFs and hows. So out of context i might imply this but that was not my intention, sorry.. But now i know from your answers i get it and i agree with it. I hope that this will be a more progressing project soon. So my frustration is gone. I will contribute if i can.

Thank you.

**Comment by broxen** [comment]
Thank you again @kwantumhab. I apologize for confusing your post with @Baaleos. My mistake. I appreciate both of your feedback. I don't think anyone is offended. 

Glad I was able to shed some light on this topic. Thank you both.

**Comment by broxen** [comment]
Closing this as I think enough time has passed that any confusion is behind us.
