### ISSUE TITLE
Reorganize Repos and Clean Up Folder Structures

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#916]
## Feature Summary
With renewed focus for the project, we should reorganize the repo and folder structures.

### Proposed Implementation
Overall, the repo layout could be changed to something like:
- SegsEngine
- Segs
  - Server
  - Client-code
  - Launcher
  - Editor
  - Web-tooling
- SegsAssets
  - Client-asset sources ( needs some thinking about the git-lfs vs other ways of tracking larger assets)
  - Web assets ( images, icons, logos)
  - Editor-assets
- A sub-project to handle add-ons, basically a clone of https://godotengine.org/asset-library/asset
- Remove the references to other-never-touched mmo emulators 

Only loosely related to #839

**Comment by miles200** [comment]
@broxen Something like this? Any preference? 

![image](https://user-images.githubusercontent.com/35471210/78369550-44195100-75bd-11ea-8461-8950fe6b9066.png)

**Comment by nemerle** [comment]
The one on the right looks better + I'd modify this a bit:
* `include` directory + contents likely should be relocated to `Common/` and `3rd_party` as needed
* It's likely `Data/` contents should be split/pushed into their respective 'owning' directories (Servers/Client/Launcher/etc.)
* `contrib` directory should be removed ( right now its just a PHP password hasher help function -> should be moved to WebTooling ? )
* could consider moving `CMakeScripts`, `ci_support` and `docker` directories into an umbrella of `BuildAndDeploy` - note: would require a few small changes in root CMakeLists.txt
* `Launcher` could likely be moved into Client directory
*  `Utilities` could be fixed up a bit as well, for example, `event_gen` likely could be moved to `BuildAndDeploy` since it's only used during the build.
* merging doc directories is good, but maybe we should still have the internal hierarchy ( docs/Client docs/Servers/MapServer, docs/Build, docs/Deployment, etc. )

**Comment by miles200** [comment]
> 
> 
> The one on the right looks better + I'd modify this a bit:
> 
>     * `include` directory + contents likely should be relocated to `Common/` and `3rd_party` as needed
> 
>     * It's likely `Data/` contents should be split/pushed into their respective 'owning' directories (Servers/Client/Launcher/etc.)
> 
>     * `contrib` directory should be removed ( right now its just a PHP password hasher help function -> should be moved to WebTooling ? )
> 
>     * could consider moving `CMakeScripts`, `ci_support` and `docker` directories into an umbrella of `BuildAndDeploy` - note: would require a few small changes in root CMakeLists.txt
> 
>     * `Launcher` could likely be moved into Client directory
> 
>     * `Utilities` could be fixed up a bit as well, for example, `event_gen` likely could be moved to `BuildAndDeploy` since it's only used during the build.
> 
>     * merging doc directories is good, but maybe we should still have the internal hierarchy ( docs/Client docs/Servers/MapServer, docs/Build, docs/Deployment, etc. )

Cheers @nemerle

**Comment by broxen** [comment]
I think this is complete? I can close?

**Comment by nemerle** [comment]
Yup
